apiVersion: v1
kind: Secret
metadata:
  namespace: minio
  name: juicefs-minio-secret
type: Opaque
stringData:
  name: "data"
  metaurl: "redis://redis.minio.svc.cluster.local/1"
  storage: "minio"
  bucket: "http://minio.minio.svc.cluster.local:9000/juicefs"
  access-key: "minio"
  secret-key: "minio123"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-minio
provisioner: csi.juicefs.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-minio-secret
  csi.storage.k8s.io/node-publish-secret-namespace: minio
  csi.storage.k8s.io/provisioner-secret-name: juicefs-minio-secret
  csi.storage.k8s.io/provisioner-secret-namespace: minio
