apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  # https://metallb.universe.tf/installation/
  # https://github.com/metallb/metallb/tree/v0.14.8/config/native
  - github.com/metallb/metallb/config/native?ref=v0.14.8

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: metallb
