apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mlb1
  namespace: metallb-system
spec:
  addresses:
    - ${netId}220-${netId}250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mlb1
  namespace: metallb-system
spec:
  ipAddressPools:
    - mlb1
