#!/bin/bash

RAW='https://raw.githubusercontent.com/yang-lin94/svr-config/refs/heads/main'

# Define a list of folders to exclude
EXCLUDE_DIRS=("k8s")

# Generate root README.md
echo '' >README.md
for model in $(ls -d */ | sed 's|/||g'); do
  # Check if the current folder is in the exclusion list
  if [[ ! " ${EXCLUDE_DIRS[@]} " =~ " ${model} " ]]; then
    ls ${model}/ | grep '\.' >${model}/model_name

    # Add directory link to root README.md
    echo "# ${model}" >>README.md
    echo '' >>README.md
    echo "查看 [${model}](${model}) 的安裝腳本" >>README.md
    echo '' >>README.md

    # Generate README.md for each model directory
    echo '' >${model}/README.md
    while read name; do
      echo "# ${name}" >>${model}/README.md
      echo '' >>${model}/README.md
      echo '```bash' >>${model}/README.md
      echo "wget -qO - ${RAW}/${model}/${name}/${name}.txt | sudo bash" >>${model}/README.md
      echo '```' >>${model}/README.md
      echo '' >>${model}/README.md
    done <${model}/model_name
  fi
done
