apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  # https://juicefs.com/docs/zh/community/juicefs_on_k3s/#%E5%AE%89%E8%A3%85-csi-driver
  - https://raw.githubusercontent.com/juicedata/juicefs-csi-driver/master/deploy/k8s.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: StatefulSet
      name: juicefs-csi-controller

  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        namespace: kube-system
        name: juicefs-csi-node
      spec:
        template:
          spec:
            containers:
              - name: juicefs-plugin
                env:
                  # https://github.com/juicedata/juicefs-csi-driver/pull/680
                  - name: JUICEFS_IMMUTABLE
                    value: "true"

