apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

resources:
  - https://raw.githubusercontent.com/yandex-cloud/k8s-csi-s3/refs/heads/master/deploy/kubernetes/driver.yaml
  - https://raw.githubusercontent.com/yandex-cloud/k8s-csi-s3/refs/heads/master/deploy/kubernetes/provisioner.yaml
  - https://raw.githubusercontent.com/yandex-cloud/k8s-csi-s3/refs/heads/master/deploy/kubernetes/csi-s3.yaml
