apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

resources:
  - redis-svc.yaml
  - redis-dep.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: km1
    target:
      kind: Deployment
      name: redis