# https://github.com/kubernetes/examples/blob/master/staging/storage/redis/README.md
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minio
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: redis # has to match .spec.selector.matchLabels
    spec:
      hostname: redis
      containers:
        - name: redis
          image: docker.io/redis:alpine3.20
          imagePullPolicy: IfNotPresent # Always, Nerver, IfNotPresent
          resources:
            requests:
              cpu: "0.5"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "2048Mi"
          volumeMounts:
            - name: redis
              mountPath: /data
      volumes:
        - name: redis
          hostPath:
            path: /opt/redis
      restartPolicy: Always
