apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
	name: "km1"
	criSocket: ${criSocket}
	taints: null
localAPIEndpoint:
	advertiseAddress: ${IP}
	bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
etcd:
	local:
	  dataDir: "/var/lib/etcd"
networking:
	serviceSubnet: "10.98.0.0/24"
	podSubnet: "10.244.0.0/16"
	dnsDomain: "cluster.local"
kubernetesVersion: ${kubeversion}
controlPlaneEndpoint: ${vip}
apiServer:
	timeoutForControlPlane: 4m0s
controllerManager: {}
scheduler: {}
certificatesDir: "/etc/kubernetes/pki"
imageRepository: "registry.k8s.io"
clusterName: ${clustername}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 110
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs