name: Run and Commit Script Changes

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run script and push changes
        id: run-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Start."
          ./list
          # Configure git
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]

          # Check if there are any changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Update README.md"
            git push origin main
            echo "Changes committed and pushed successfully."
          else
            echo "No changes to commit."
          fi

